# Generated by Django 4.2.16 on 2024-11-03 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('documentId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=300)),
                ('image', models.URLField(max_length=300)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('publishedAt', models.DateTimeField()),
            ],
        ),
    ]
