# Generated by Django 4.2.16 on 2024-11-04 12:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('documentId', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(max_length=300)),
                ('publisher', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.URLField(blank=True, max_length=300, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('publishedAt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
