# Generated by Django 4.2.16 on 2024-11-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
