# Generated by Django 4.2.16 on 2024-11-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_name_book_title_remove_book_documentid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publishedAt',
        ),
    ]
