# Generated by Django 4.2.16 on 2024-11-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_publishedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishedAt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
