# Generated by Django 4.2.16 on 2024-11-05 06:15

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book',
            field=models.FileField(default='default.epub', storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/kislosladky/Documents/Study/SoftwareDesign/DigitalLibrary/django/media')), upload_to='books/'),
        ),
    ]
