# Generated by Django 4.2.16 on 2024-11-05 06:25

import django.core.files.storage
from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(default='books/default.epub', storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/kislosladky/Documents/Study/SoftwareDesign/DigitalLibrary/django/media')), upload_to='books/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/Users/kislosladky/Documents/Study/SoftwareDesign/DigitalLibrary/django/media')), upload_to='images/'),
        ),
    ]
