# Generated by Django 5.1.2 on 2024-11-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_book_alter_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book',
            new_name='bookFile',
        ),
    ]
